apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "twitsss.fullname" . }}
  labels:
    app: {{ template "twitsss.name" . }}
    chart: {{ template "twitsss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "twitsss.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "twitsss.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
      {{- range .Values.scrapers }}
        - name: {{ .description }}
          image: "{{ $.Values.scraper.repository }}:{{ $.Values.scraper.tag }}"
          imagePullPolicy: {{ $.Values.scraper.pullPolicy }}
          volumeMounts:
          - name: data
            mountPath: {{ $.Values.persistence.mountPath }}
            subPath: {{ .description }}
          env:
          - name: "TWITTER_CONSUMER_KEY"
            value: {{ .twitterConsumerKey }}
          - name: "TWITTER_CONSUMER_SECRET"
            valueFrom:
              secretKeyRef:
                name: "{{ $.Release.Name }}-secrets"
                key: "twitter-consumer-secret-{{ .description }}"
          - name: "TWITTER_ACCESS_KEY"
            value: {{ .twitterAccessKey }}
          - name: "TWITTER_ACCESS_SECRET"
            valueFrom:
              secretKeyRef:
                name: "{{ $.Release.Name }}-secrets"
                key: "twitter-access-secret-{{ .description }}"
          - name: "BOUNDING_BOX"
            value: {{ .boundingBox }}
          - name: "DATA_PATH"
            value: {{ .description }}
          - name: "BUFFER_SIZE"
            value: !!str {{ .bufferSize }}
          - name: "GEO_ONLY"
            value: !!str {{ .geoOnly }}
      {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ template "twitsss.fullname" . }}

