---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $.Release.Name }}-secrets"
  labels:
    app: {{ template "twitsss.name" . }}
    chart: {{ template "twitsss.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  type: Opaque
data:
  {{- range .Values.scrapers }}
  "twitter-consumer-secret-{{ .description }}": {{ .twitterConsumerSecret | b64enc | quote }}
  "twitter-access-secret-{{ .description }}": {{ .twitterAccessSecret | b64enc | quote }}
  {{- end }}