---
- name: Build and run tweet scraper docker image (assume docker is installed)
  hosts: scraper
  tasks:
    - name: upload the app directory to the docker host
      synchronize: src=../scraper dest=/tmp

    - name: build the image
      command: docker build -t scraper:v0.1 /tmp/scraper
      become: true

    - name: Run the docker container
      docker_container:
        name: scraper
        image: scraper:v0.1
        env:
            PROD=True
      become: true

